[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_lend_borrow = "43mrJ7631xbt5DZGJemvk5TqSR3g4EMjxBd3Sh2BdukJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
